### ISSUE TITLE
Deployment instructions & license

### ISSUE THREAD

**Issue by blokhin** [ScienceSight/Graphs#2]
Dear @DmitryAI @ScienceSight thanks for your professional work 👍

Please, could you add the deployment instructions? Consider writing it as for your grandma :)

I'll also write a separate email to Andrey concerning the distribution license.

**Comment by DzmitryBratchuk** [comment]
Hi @blokhin please check linked PR

**Comment by blokhin** [comment]
Excellent! Thanks much 🙏

**Comment by blokhin** [comment]
Please, merge.
