### ISSUE TITLE
Checking *graphName* field for non-ascii symbols

### ISSUE THREAD

**Issue by blokhin** [ScienceSight/Graphs#25]
Generally, it would be helpful to prohibit any non-ascii symbols in the graph titles.

**Comment by blokhin** [comment]
@DzmitryBratchuk

**Comment by blokhin** [comment]
@DzmitryBratchuk should this be closed?

**Comment by blokhin** [comment]
🚀

**Comment by DzmitryBratchuk** [comment]
> @DzmitryBratchuk should this be closed?

@blokhin Now it can be closed 😺

**Comment by blokhin** [comment]
@DzmitryBratchuk many thanks 👍
