### ISSUE TITLE
Parent form status is always INVALID

### ISSUE THREAD

**Issue by blokhin** [ScienceSight/Graphs#8]
Hi! I tried to upload some graph, to input some values, to select some points, bit the button "Save As ..." is still defunct.

Please see the screen-shot attached. What should I do?

![2020-06-12_14-47-43](https://user-images.githubusercontent.com/177388/84604294-43dae300-ae95-11ea-8647-96d3c102a019.png)

**Comment by blokhin** [comment]
@DmitryAI @DzmitryBratchuk please assist.

**Comment by DzmitryBratchuk** [comment]
@blokhin  My apologize, I haven't seen a new open issue.
You should also set 'Origin', 'X-axis' and 'Y-axis' points. Now these buttons are 'toggle buttons', so click on 'Origin', then on canvas, then again on 'Origin'. The actions with 'X-axis' and 'Y-axis' are the same.

**Comment by blokhin** [comment]
Sorry, it still does not work.

What I do, step by step, following the README and the instruction Andrey sent me:

- `ng serve`
- open browser window at http://localhost:4200
- click "Choose .png file", load some fake PNG
- input `X-axis name` **test** and `Y-axis name` **test**
- input `Origin` X **123** and Y **123**
- input X-axis **123** and Y-axis **123**
- add some random points (they are connected with the red line)
- name sub-graph **test**

And nothing happens. `Parent Form Status: INVALID`

**Comment by DzmitryBratchuk** [comment]
@blokhin Could you send screenshot?

**Comment by blokhin** [comment]
![2020-06-28_19-30-27](https://user-images.githubusercontent.com/177388/85954182-e4410500-b975-11ea-93fd-c372459b05b2.png)

Just a test! I cannot figure out, how to save some points for testing.

**Comment by blokhin** [comment]
Also, what should be selected as **.csv** file?

**Comment by DzmitryBratchuk** [comment]
In this screenshot only one point is set (Origin or X-axis or Y-axis). You should set all of them. 
Andrew send updated instruction to you.

**Comment by blokhin** [comment]
Alright, I figured it now. The requirement to press "Origin" or "X-axis" or "Y-axis" buttons was **_very unclear_**.

Please, set the verbs to the buttons instead: "Set origin", "Set X-axis", "Set Y-axis". This will improve the first-time experience dramatically.
